---
- name: Install StackStorm
  hosts: st2
  strategy: debug
  vars:
    st2_pkg_repo: staging-unstable
    st2_auth_username: st2admin
    st2_auth_password: st2pass

  roles:
    - mongodb
    - rabbitmq
    - st2repos
    - mistral
    - st2
    - st2web
    - st2smoketests
