---

- name: "Provision Docker Swarm Cluster"
  hosts: all
  vars:
    # For Vagrant, uncomment the line
    docker_swarm_interface: "eth1"
    skip_docker_py: True
  roles:
    - role: ansible-dockerswarm
