---
name: on_pending_scaleup_openstack
pack: swarm
description: "Scale up the Swarm when pending tasks go over threshold."
enabled: False

trigger:
    type: swarm.pending_tasks
    parameters: {}

criteria:
    # Crossing threshold up
    trigger.over_threshold:
        type: equals
        pattern: True

action:
    ref: swarm.scale_openstack
    parameters:
        webhook: "https://webhook_url_specific_to_the_asg_for_scale_up"
