---
name: scale_out_test
pack: swarm
description: "Test scale-in rule, fires  on swarm pending task queue count going UP ABOVE threshold"
enabled: True

trigger:
    type: swarm.pending_tasks
    parameters: {}

criteria:
    # Crossing threshold up
    trigger.over_threshold:
        type: equals
        pattern: True

action:
    ref: core.local
    parameters:
        cmd: "echo Pending queue going up: {{ trigger.count }}"

